package ru.demi.model;

import lombok.Data;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import java.math.BigDecimal;

@Entity
@Data
public class Bid {

    @Id
    @GeneratedValue
    private Long id;

    private BigDecimal amount;

    @ManyToOne(cascade = CascadeType.ALL)
    // @JoinColumn(name = "item_id") is generated by default
    private Item item;
}
